### ISSUE TITLE
No reply button on comments

### ISSUE THREAD

**Issue by ramu-r** [rystaf/mlmym#1]
Hey,

Awesome work. I was blown away by how good it feels and everyone I showed it to shared the same opinion. This is miles ahead of every lemmy frontend or template I have seen.

An issue I noticed was, I couldn't find any reply buttons for comments left by others but there are reply buttons for my own comments under posts. I tried to append a '?reply' to the permalink of comments by others and that seems to work. It seems like it's something missing in the templates.

I was connected to a lemmy instance through mlmym.org. I don't know if it's some internal setting that can be changed in a self hosted instance. I am yet to try that.

**Comment by rystaf** [comment]
Thanks so much for the great feedback! Happy to hear someone else is enjoying it.
I just pushed a fix for the replies link. Small bug that happened when I implemented the edit button.
