### ISSUE TITLE
Register Image Link as Clicked when expanded

### ISSUE THREAD

**Issue by Syer10** [rystaf/mlmym#103]
Basically the same type of thing if you clicked the image link with your mouse, but automatic after expanding the image.

Here is an example of what I would like.

Going from this
![image](https://github.com/rystaf/mlmym/assets/6090655/d4846413-5871-48fb-a82d-b5d9886f1fca)
To this after clicking the image expand icon
![image](https://github.com/rystaf/mlmym/assets/6090655/f27ab4ae-57d2-4cb6-be93-4c2ea0e5d8b8)
Reddit or RES does this automatically and this is how I used to know if I have already seen this post.

**Comment by rystaf** [comment]
I added an option in the latest release 0.0.42 for this. It only works when signed in.
