### ISSUE TITLE
Mark image as read disappears after refresh

### ISSUE THREAD

**Issue by Syer10** [rystaf/mlmym#106]
My instance updated to 0.19.4 recently, so this might have to do with that. I've tested remote and local links and it seems to happen to both.

**Comment by rystaf** [comment]
What is disappearing after refresh?

**Comment by rystaf** [comment]
Gotcha. Yeah you were right about the update. Looks like [they removed the single post_id](https://github.com/LemmyNet/lemmy/commit/87b577467be74637881e1a22eba39349232f0a77) property we were using. Thankfully the multiple post_ids property is backwards compatible. Fix will be out in the next release.

**Comment by Syer10** [comment]
@rystaf my instance updated to 0.0.48 and its still not fixed
