### ISSUE TITLE
Make changes from old reddit style optional

### ISSUE THREAD

**Issue by CalcProgrammer1** [rystaf/mlmym#15]
Rather than just making changes that stray away from the old reddit style, it would be nice if they were optional.  The theme changes (green instead of blue, reversed colors for upvote and downvote) could be made into a selectable theme in settings so we could choose to keep the old reddit accurate style.

Also, it would be nice if the "load more" button was optional, leaving the ability to have next/prev pages.  I've never been a fan of infinite scrolling pages.

**Comment by thantik** [comment]
Infinite scrolling pages can be turned off in the settings, and is a feature of RiF, which I assume most people migrating probably used.  I forgot that next/prev buttons even existed until I moved over.
