### ISSUE TITLE
Display Imgur thumbnails

### ISSUE THREAD

**Issue by pintassilgo** [rystaf/mlmym#17]
Currently there's no thumbnail for posts of Imgur links.

Imgur has native thumbnails by appending a letter following the ID.

Example:

- Original: https://i.imgur.com/rHBpPyx.jpg
- s (90x90): https://i.imgur.com/rHBpPyxs.jpg
- b (160x160): https://i.imgur.com/rHBpPyxb.jpg
- t (160x160 keeping aspect ratio): https://i.imgur.com/rHBpPyxt.jpg

Source: https://api.imgur.com/models/image

**Comment by rystaf** [comment]
Thanks for the tip!
