### ISSUE TITLE
Pagination in posts list

### ISSUE THREAD

**Issue by pintassilgo** [rystaf/mlmym#18]
One important feature from old.reddit I'm missing are pagination links for home and community pages. Currently, mlmym has only the "*load more*" button which appends more results on the current page, also it doesn't have a link to previous page.

**Comment by rystaf** [comment]
until we get a better settings menu going, for what it's worth, you can get the pagination "next" and "prev" buttons back if you disable javascript in your browser (with an extension like noscript or uMatrix)

**Comment by RandomUsername404** [comment]
I'd like a way to disable infinite scrolling, too.
