### ISSUE TITLE
[Feature request] Add picture upload for comments

### ISSUE THREAD

**Issue by bwachter** [rystaf/mlmym#22]
Seems I currently can't upload pictures while writing a comment. Probably would be sensible to do that together with the markdown bar suggested here: https://github.com/rystaf/mlmym/issues/5#issuecomment-1622655909

**Comment by rystaf** [comment]
added in https://github.com/rystaf/mlmym/commit/6c80f67535aedd6abc2d7ed2fb9cbf64a82d46c6
