### ISSUE TITLE
archive threads for offline viewing

### ISSUE THREAD

**Issue by jadedgnome** [rystaf/mlmym#24]
save threads including images. for offline viewing.

**Comment by rystaf** [comment]
Would something like this be sufficient? https://addons.mozilla.org/en-US/firefox/addon/save-page-we/
If not is there some other forum/website with similar functionality you could point me to?

**Comment by jadedgnome** [comment]
sure but I was thinking something like this https://github.com/pl77/redditPostArchiver this but single file.

![image](https://github.com/rystaf/mlmym/assets/2940805/502eb5d7-3745-434e-be56-607cbc839821)

**Comment by rystaf** [comment]
I think this functionality would be best suited outside of the mlmym project
