### ISSUE TITLE
Unexpected pagination in comments

### ISSUE THREAD

**Issue by pintassilgo** [rystaf/mlmym#29]
In #18 I asked to add pagination in posts list, thanks for that, but the side effect was adding pagination to comments as well. This was unexpected and now the experience for reading posts with many comments isn't good.

In old reddit, I'm used to load 500 comments by default. Not sure about Lemmy API limits, the number can be lower, but at least I propose a `load more comments` button just like old Reddit instead of pagination links.

**Comment by RandomUsername404** [comment]
If we could have an "auto load more comments" setting, too, that'd be neat.
