### ISSUE TITLE
Feature request: click and drag to resize

### ISSUE THREAD

**Issue by Avenred** [rystaf/mlmym#43]
With RES, you could click and drag an image preview left or right to resize. I'd like to see this added to mlmym.

https://github.com/rystaf/mlmym/assets/13921970/c1c554a1-de01-473a-b7b9-ce6f06972159

**Comment by rystaf** [comment]
Added in latest release 0.0.34

**Comment by Crul** [comment]
@rystaf The feature is broken on my environment, it does resize the images when you click&drag, but it does not stop when you release the mouse button.

- Server: latest docker image (0.34)
- Cliente: Win10 + Firefox

**Comment by rystaf** [comment]
@Crul Haven't been able to reproduce that yet, but does the latest release 0.0.35 fix it for you?

**Comment by Crul** [comment]
@rystaf Indeed, 0.0.35 fixed it!

Thanks
