### ISSUE TITLE
strange behavior when I deleted a post on Lemmy: the whole page I was looking at for the Community was duplicated within itself (see attached image)

### ISSUE THREAD

**Issue by GoodKingElliot** [rystaf/mlmym#48]
it happened when I was posting on a pics community.

I deleted post because there was an error (the image was sideways), and this happened:

![image](https://github.com/rystaf/mlmym/assets/140516136/d2d3a042-244e-4df0-ac5e-341b7593168c)

(NB: I had had 2 image posts, and I deleted one of them. It was deleted successfully, butgot replaced by a rendering of the whole page.)

this happened 24 July 2023

**Comment by rystaf** [comment]
this is likely fixed now, please let us know if you see it again
