### ISSUE TITLE
Clarification on license variant

### ISSUE THREAD

**Issue by Cellesti** [rystaf/mlmym#50]
Hi, i am thinking of packaging Mlmym for Alpine linux, and would like some clarification on which variant of AGPL-3.0 Mlmym is under.

The `AGPL-3.0` license identifier has been [deprecated](https://spdx.org/licenses/AGPL-3.0.html) by SPDX.

So, i would appreciate it if you could tell me whether you are using `AGPL-3.0-or-later` or `AGPL-3.0-only`.

Thank you.

**Comment by rystaf** [comment]
AGPL-3.0-or-later
