### ISSUE TITLE
Expose Community 'edit', 'delete' buttons in old skin

### ISSUE THREAD

**Issue by Russtopia** [rystaf/mlmym#51]
Nice work, thanks for this! :100: :1st_place_medal: 

If I'm the mod of a community, there is an Edit and Delete button in the upper-right, just below the name of the community:

![image](https://github.com/rystaf/mlmym/assets/2966177/85692e51-c33e-423b-ac6e-6e6bd3e88292)

It would be really nice to have these exposed in the 'old' CSS skin so one can edit community description text without switching back to the default lemmy view.

**Comment by rystaf** [comment]
You can edit the community description with the community settings link at the bottom of the side bar
![image](https://github.com/rystaf/mlmym/assets/2389047/06eb18e2-ad54-4818-a225-9591c39565d3)

**Comment by Russtopia** [comment]
> You can edit the community description with the community settings link at the bottom of the side bar ![image](https://user-images.githubusercontent.com/2389047/256348379-06eb18e2-ad54-4818-a225-9591c39565d3.png)

Oh! I see now. Thank you, my apologies for missing that. Awesome.
