### ISSUE TITLE
Not all subscribed communities show up in the subscribed dropdown

### ISSUE THREAD

**Issue by Zamboniman** [rystaf/mlmym#55]
In the dropdown list of subscribed communities, not all of the communities I am subscribed to are showing up there. For example, I am subscribed to worldnews@lemmy.ml, worldnews@beehaw.org, and worldnews@lemmy.world, but the only one of these three that shows up in the dropdown is worldnews@lemmy.ml.

**Comment by rystaf** [comment]
Could you tell me what your home server is and how many communities you're subscribed to? Wondering if this is a paging issue.

**Comment by Zamboniman** [comment]
My home server is lemmy.ca, and I'm subscribed to 68 communities atm (yeah, lots).

**Comment by rystaf** [comment]
Weird, I can't reproduce it. I went and subscribed to 72 communities on lemmy.ca, including those worldnews communities, and all are listed for me.
![image](https://github.com/rystaf/mlmym/assets/2389047/3a29a610-a241-4e40-90b6-41349e712e18)

Do those worldnews communities show up when you search like this? 
https://lemmy.ca/search?q=worldnews&type=Communities&listingType=Subscribed&page=1&sort=TopAll

**Comment by rystaf** [comment]
Ah I think I see what's up. worldnews@beehaw.org doesn't exist. It's actually news@beehaw.org but the display name is world news.

**Comment by Zamboniman** [comment]
Okay, that makes sense for news@beehaw.org, but to answer your question about if worldnews@lemmy.world shows up in a search on my instance, oddly enough it *doesn't*. Which is very odd since I am quite sure it showed up there before and it works fine when I actually go to lemmy.ca/c/worldnews@lemmy.world, so I dunno. 

Edit:

I tried unsubscribing and resubscribing to worldnews@lemmy.world, and now it shows up. So given that information, this sounds a bit more like a lemmy bug than a mlmym bug.
