### ISSUE TITLE
Enable click and drag to resize images

### ISSUE THREAD

**Issue by Starmann** [rystaf/mlmym#56]
This is probably the only feature from RES that I used regularly. And it was absolutely essential. Sometimes images would load too big or too small. This allowed manual adjustments.

**Comment by rystaf** [comment]
duplicate #43

**Comment by neilsimp1** [comment]
I am confused, did this get implemented? I can make images smaller but not larger (Firefox).

**Comment by rystaf** [comment]
Added in latest release 0.0.34
