### ISSUE TITLE
Public instance: o.opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [rystaf/mlmym#59]
Hi, great app! Not sure if you're planning to add a list of public mlmym instances in this repo. Here's mine in case anyone is interested. Thanks!

[o.opnxng.com](https://o.opnxng.com/) 
Hosted in Singapore
[Contact/privacy](https://about.opnxng.com/)

**Comment by rystaf** [comment]
Thanks for sharing!
This info would be best stored in something like https://github.com/maltfield/awesome-lemmy-instances
