### ISSUE TITLE
[Bug Report] My randomly generated password seems to reliably break the login process

### ISSUE THREAD

**Issue by Zistack** [rystaf/mlmym#65]
I generated my password with keepassxc, using all character classes but non-printables, and a length of 128 characters.  The login form always kicks back a `400 Bad Request: incorrect_login` when I try to log in, even though I'm pasting in the information from my password manager.  Moreover, the same credentials on the default frontend work just fine.

**Comment by rystaf** [comment]
Is this still happening for you? There was a bug that was fixed in version 0.0.46 that caused 400 errors when logging in with your email address instead of your username.

**Comment by Zistack** [comment]
The error message has changed.  I now get a `401: Unauthorized: incorrect_login`.  I just double-checked that my login credentials were still correct by logging into the same lemmy server via the default interface.

**Comment by rystaf** [comment]
This might be related to https://github.com/LemmyNet/lemmy-ui/issues/1120
Try using just the first 60 characters of your password.

**Comment by Zistack** [comment]
That worked.  Am I to understand that this means that the default interface is actually silently truncating my password to 60 characters when I either set it or go to log in?
