### ISSUE TITLE
[Feature Request] Block Users, Block Subs without having to visit the sub?

### ISSUE THREAD

**Issue by thantik** [rystaf/mlmym#68]
Apologies but I don't know what the equivalent to a 'subforum' or 'subreddit' would be on the fediverse.

But the old UI does not have any way to block users, and blocking subs requires you to visit that sub in order to block it.

So...for example -- I want to block horse-pron because it's showing up in /all. In order to do so from this interface, I have to **visit** the sub for horse pron in order to do so... which is quite offputting because there's no ability to block the sub from the post itself.

Blocking a user, I cannot seem to find an interface element to do so.  I've looked on user pages, I've looked on posts, on replies to comments.  I can't seem to find it.  So I have to revert to someone elses UI, log in there, block the person, and then come back to mlmym.

**Comment by rystaf** [comment]
added block button in latest release [0.0.28](https://github.com/rystaf/mlmym/releases/tag/0.0.28)

**Comment by thantik** [comment]
You are an absolute god.  No less can be said about you.  Thank you!
