### ISSUE TITLE
Mlmym is no longer showing my subscribed communities

### ISSUE THREAD

**Issue by ToughPapaya** [rystaf/mlmym#69]
When I go to subscribed, I get this message: "there doesn't seem to be anything here." And if I click on the "My communities" tab in the top bar, there are no communities listed. But if I go to my instance's URL and navigate to subscribed, I can see posts from communities I'm subscribed to.

Browser: Chrome
Browser Version: Version 115.0.5790.171 (Official Build) (64-bit)
OS: Windows 10

**Comment by ammargitham** [comment]
Try clearing cookies named 'jwt' and refresh. For me there were 2 cookies with the same name. You'll have to re-login after this. I think that was causing the problem.

**Comment by rystaf** [comment]
Let us know if this is still happening for you.
