### ISSUE TITLE
Images displayed using Expand button cannot be copied/saved on page, must be opened in new tab/window to save/copy

### ISSUE THREAD

**Issue by yukichigai** [rystaf/mlmym#78]
When displaying images on the community/main page using the Expand button, the full image will be displayed, but it is not possible to copy/save/etc. the image using the right-click menu as one would normally expect to be able to. For browsers that do offer a "save" or "save as" option, what is saved is an html file rather than an image. Opening the link directly will allow it to be saved, as will the "Open Image in New Tab" option in Firefox (which bizarrely is available even though no other image-related menu options are).

Images display just fine otherwise, but anyone wanting to save things they spot on Lemmy has to perform an extra step or two. Low priority, to say the least.

**Comment by oneguynick** [comment]
My hunch was that the image format was being loaded as `*.webp`, but it looks like the image is, in fact jpeg.

I tested the following browsers with clean profiles with the same issue:

- [X] Firefox 
- [X] Safari
- [X] Chrome

Its annoying, but not a high priority, as @yukichigai stated. Its a creature comfort at best for those of us sharing memes.

**Comment by rystaf** [comment]
fixed in latest release 0.0.34
