### ISSUE TITLE
Support New Auth changes in 0.19

### ISSUE THREAD

**Issue by DraconicNEO** [rystaf/mlmym#91]
Lemmy 0.19 has updated Auth protocols that render current clients unusable unless they are updated to support the new system. It would be great if mlmym was updated to support the new version so it'll work properly upon the official release.

**Comment by rystaf** [comment]
> current clients unusable

It look like the current version of mlmym still works with 0.19. Though I do agree we should update the Auth protocols.

![image](https://github.com/rystaf/mlmym/assets/2389047/8c354874-ad65-4c5c-962e-947e90d93661)

**Comment by rystaf** [comment]
Fixed with latest release 0.0.31
