### ISSUE TITLE
Intermittent "rate_limit_error" and "unable to retrieve site".

### ISSUE THREAD

**Issue by perestroika-pw** [rystaf/mlmym#92]
I don't have quality information for debugging this, but I've experienced two issues with "old.slrpnk.net", and the admin of that site advised me to report them here.

> "400 Bad Request: rate_limit_error. there doesn't seem to be anything here" - when accessing communities

> "unable to retrieve site. there doesn't seem to be anything here" - when accessing a user profile, once

These two have occurred occasionally. They go away with refreshing. They are difficult to reproduce at will - appearing at seemingly random times. When one is happening, it seems that the other is also likely.

**Comment by Demigodrick** [comment]
This is probably down to your server's nginx config. It's something your admin needs to fix, by relaxing the rate limiting in the config file.
