### ISSUE TITLE
Logging into mlmym forced all messages in the normal lemmy UI to be marked as read

### ISSUE THREAD

**Issue by Commander-Zal** [rystaf/mlmym#93]
Hello!

My instance slrpnk.net has mlmym as an alternative frontend. However, after logging in and experimenting with it, I found that all of the messages/replies in my inbox were marked as read (before logging into the other front end, I had 150 unread messages), and my inbox was set to unread messaged only.

The actions that I did before that happened: 

- Changed to dark theme in settings
- clicked on the comments for a post
- Went to my inbox

**Comment by rystaf** [comment]
opening your inbox in mlmym will mark all messages as read
