### ISSUE TITLE
Profile Overview not showing latest elements on 0.0.33

### ISSUE THREAD

**Issue by Crul** [rystaf/mlmym#95]
Environment:

- mlmym 0.0.33
- deployed on docker
- `LEMMY_DOMAIN='lemm.ee'`

Problem: The overview page in the user profile (mlmym.instance/u/username) does not show the latest elements that are visible in http://lemmy.instance/u/username.

It looks like a cache issue because the posts and comments end up being shown on mlmym after a while.

**Comment by rystaf** [comment]
mlmym doesn't do any caching on its own. it displays what's returned from the lemmy api.
