### ISSUE TITLE
Expanded image gets clipped on mobile screens

### ISSUE THREAD

**Issue by devprog-cpu** [rystaf/mlmym#96]
When expanding an image mobile screen, it is aligned right, and clipped from the screen, while leaving empty space on left.
Until a few days before, it used to expand properly.

![lemmy](https://github.com/rystaf/mlmym/assets/152577509/c6e165e4-12df-40a7-b45e-e5c9942f28a8)

**Comment by rystaf** [comment]
fixed in latest release 0.0.35
