### ISSUE TITLE
Blank page on ARM

### ISSUE THREAD

**Issue by extremelyonline** [rystaf/mlmym#97]
Hello, my [public instance](o.opnxng.com) stopped working a while ago. A blank page was shown instead of the homepage. There is no error in the container log.

I was using `ghcr.io/rystaf/mlmym:latest`. My servers are on ARM architecture. I suspect this issue maybe specific to ARM, would anyone else please confirm?

Currently, I rolled back to `ghcr.io/rystaf/mlmym:0.0.30`, which works.

**Comment by rystaf** [comment]
fixed in latest release 0.0.36
