### ISSUE TITLE
Please add support for .webp images

### ISSUE THREAD

**Issue by Scotty-Trees** [rystaf/mlmym#99]
When browsing the main old.lemmy.world homepage, when clicking the plus sign, it expands images like pngs just fine. But when the image is a webp image, it loads nothing. And when I click the headline of the article that directs to the webp image, I get an error thrown out that looks like the following. Please let me know if you need any more information. This was tested on Firefox 121 on Fedora 39 Gnome with mlmym v0.0.30

![Screenshot from 2024-01-12 13-31-39](https://github.com/rystaf/mlmym/assets/45135187/f5e1b886-5c50-4573-9756-cd71c463fb49)

![Screenshot from 2024-01-12 13-30-22](https://github.com/rystaf/mlmym/assets/45135187/64a91260-9950-4e51-9df6-e7a184cfca62)

**Comment by ollytom** [comment]
Looks like a server-side problem with lemmy.zip. In the screenshot you posted, the error message reports being unable to connect to a backend service Lemmy uses to serve pictures.

webp seems to be supported ok; see https://old.programming.dev/post/12679593
(for me running OpenBSD 7.5,  Firefox 124.0.1)
